[allowlist]
description = "Allow bcrypt hashes used in SQL updates"

regexes = [
  # Ignore bcrypt password hashes (e.g., $2b$12$...)
  '''\$2b\$12\$[A-Za-z0-9./]{53}'''
]

paths = [
  # Ignore all example certs
  '''\/example.*\.pem$''',

  # Ignore anything with the word funkymonkey anywhere in the path (example values below)
  '''ANSWCWSGLVAUQ60L4Q4CEO3C1QAYGEXZK2VKJNI''',
  '''E6GJSHOZMFBVNHTHNB53''',
  '''MCJ61D8KQBFS2DXM56S2''',
  '''J5G7CCX5QCA8Q5XZLWGI7USJPSM4M5MQHJED46CF''',
  '''IG58PX2REEY9O08IZFZE''',
  '''2LWTWO89KH26P2CO4TWFM7PGCX4V4SUZES2CIZMR''',
  '''6XBK7QY7ACSCN5XBM3GS''',
  '''AVKBOUXTFO3MXBBK5UJD5QCQRN2FWL3O0XPZZT78''',
  '''SANSWCWSGLVAUQ60L4Q4CEO3C1QAYGEXZK2VKJNI''',
  '''WB4FUG4PP2278KK579EN4NDP150CPYOG6DN42MP6JF8IAJ4PON4RC7DIOH5UEFBP''',
  '''MXFE7NSOWPN33O7UC3THY0BN03DW940CMWTLRBE2EPTI8JPX0B0CWIIDGTI4YTJ6''',
  '''IJWZ8TIY301KPFOW3WEUJEVZ3JR11CY1''',
  '''9Q36xF54YEOLjetayC0NBaIKgcFFmIHsS3xTZDLzZSrhTBkxUc9FDwUKfnxLWhco6oBJV1NDBjoBcDGmsZMYPt1dSA4yWpPe/JKY9pnDcsw=''', 
  '''MXZ9DATUWRD8WCMT8AZIPYE0IEZHJJ1B8P8ZEIXC0W552DUMMTNJJH02HFGXTOVG''',
  '''CWLBVAODE61IXNDJ40GERFOZPB3ARZDRCP4X70ID1NB28AI0OOJBTR9S4M0ACYMD''',
  '''BILZ6YTVAZAKOGMD9270OKN3SOD9KPB7OLKEJQOJE38NBBRUJTIH7T5859DJL31Q''',
  '''QBFYWIWZOS1I0P0R9N1JRNP1UZAOPUIR3EB4ASPZKK9IA1SFC12LTEF7OJHB05Z8''',
  '''E6GJSHOZMFBVNHTHNB53''',
  '''postgresql://<username>:test123@172.24.10.50/quay''',
  '''postgresql://<username>:test123@172.24.10.50/example-restore-registry-quay-database''',
  '''quayadmin''',
  '''DB_URI: postgresql://restore-registry-quay-database:zLTm315muk6rz7mL4aFuLQ2Q8rAk-dB4kPHQ2WMvdyqhaZywf20503wCZfv2Ml1f15LUsDN2-0m71gnI@restore-registry-quay-database:5432/restore-registry-quay-database
''',
  '''DB_URI: postgresql://quay360-quay-database:0vrsIUYdhCnF8r-jwz7zR6gck6kcLLQhJ11u0dx1lz8YBk185P5NnqIBwtY22JArYLi3opdKJH2-w4aM@quay360-quay-database:5432/quay360-quay-database
''',
  '''XyThQKm6lMWh4O7dKdmRwMUHB9ktxPPVSRIePOY2''',
  '''VvoFhVFp8BqcOgQ9LczE''',
  '''DB_URI: postgresql://restore-registry-quay-database:zLTm315muk6rz7mL4aFuLQ2Q8rAk-dB4kPHQ2WMvdyqhaZywf20503wCZfv2Ml1f15LUsDN2-0m71gnI@restore-registry-quay-database:5432/restore-registry-quay-database
''',
  '''postgresql://quayuser:quaypass@quay-server:5432/quay''',
  '''4b1c5663-88c6-47ac-b4a8-bb594660f08b''',
  '''postgresql://example-registry-quay-database:OyC4zGhJMbi3yUzW1aIgOLQNW18r14nAcuJfbsjtrAXUVInj2JgwLskQPOutPCXMtlKr1UPTsIPqOEjV@example-registry-quay-database:5432/example-registry-quay-database''',
  '''postgresql://restore-registry-quay-database:zLTm315muk6rz7mL4aFuLQ2Q8rAk-dB4kPHQ2WMvdyqhaZywf20503wCZfv2Ml1f15LUsDN2-0m71gnI@restore-registry-quay-database:5432/restore-registry-quay-database''',
  '''postgresql://example-restore-registry-quay-database:onHl1LDsspZh4hoOL5wW1Of7GV0Kmtp2@example-restore-registry-quay-database:5432/example-restore-registry-quay-database''',
  '''postgresql://example-restore-registry-quay-database:onHl1LDsspZh4hoOL5wW1Of7GV0Kmtp2@example-restore-registry-quay-database:5432/example-restore-registry-quay-database''',
  '''zsk/j4zEOkQq+W0BQJdSufP+IackV8WICXB5zvdF''',
  '''1H36Izzc90cUNVHaiaUX''',
  '''iO1b3RUt4KKgjSimCROSPN3cEMn4TqSgsPyniMBR''',
  '''EH67NB3Y6PTBED8H0HC6UVHGGGA3ODSE''',
  '''fn37AZAUQH0PTsU+vlO9lS0QxPW9A/boXL4ovZjIFtlUPrBz9i4j9UDOqMjuxQ/0HTfy38goKEpG8zYXVeQh3lOFzuOjSvKic2Vq7xdtQsU=''',
  '''here''',
  '''here''',
  '''here''',
  '''here''',

]
